version: "3.7"

services:
  web:
    build:
      context: ./web
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./web:/go/src/web
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: meo_cloud
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_HOST: db
      TZ: "Asia/Tokyo"
    command: /bin/bash /go/src/web/tools/await_mysql_startup.sh db root root air -d
  db:
    build:
      context: ./db/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: go_web
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql/migrations:/docker-entrypoint-initdb.d
      - ./db/mysql/log:/var/log/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d
  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./reference/openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
